name: exness_clone
description: Multi-flavor trading application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  snippet_coder_utils: ^1.0.15
  intl: ^0.20.2
  fl_chart: ^1.1.0
  country_icons: ^3.0.0
  percent_indicator: ^4.2.5
  country_picker: ^2.0.27
  google_sign_in: ^7.1.1
  file_picker: ^10.2.0
  lottie: ^3.3.1
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  dart_jsonwebtoken: ^3.2.0
  go_router: ^17.0.1
  url_launcher: ^6.3.1
  android_intent_plus: ^6.0.0
  mime: ^2.0.0
  webview_flutter: ^4.13.0
  web_socket_channel: ^3.0.3
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  local_auth: ^3.0.0
  http_parser: ^4.1.2
  xml: ^6.6.1
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  msgpack_dart: ^1.0.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

dependency_overrides:
  vector_math: ^2.1.5


flutter:

  uses-material-design: true


  assets:
    - assets/image/
    - assets/image/capmarket/
    - assets/image/ellitefx/
    - assets/image/nestpip/
    - assets/image/pipzomarket/
    - assets/image/prime-forex-market/
    - assets/image/right-trade/
    - assets/image/innovixcapital/
    - assets/image/forexmt/
    - assets/image/ivrfx/
    - assets/image/enzo4ex/
    - assets/image/fynixfxweb/
    - assets/image/finfly/
    - assets/image/world-one-capital/
    - assets/image/sarthifxm/
    - assets/image/capyngen/
    - assets/image/voltfx-trade/
    - assets/image/ganecapitalfx/
    - assets/image/zyrotrade/
    - assets/image/tgrxm/
    - assets/image/valtradex/
    - assets/image/livefxm/
    - assets/image/iglobefx/
    - assets/image/ryvotrade/
    - assets/image/kitefx/
    - assets/image/bluegatemarket/
    - assets/image/nmatrixpro/
    - assets/image/fourxtradz/
    - assets/image/fxcelite/
    - assets/image/vintageprimefx/
    - assets/image/aoneprimefx/
    - assets/image/aurelianglobal/
    - assets/